### ISSUE TITLE
Consider moving cmr to NASA Github Org

### ISSUE THREAD

**Issue by lewismc** [ghrcdaac/cmr#15]
Hi Folks,
@jasonduley has been very helpful in aiding me in transitioning more of my code over to the [NASA Github Org](https://github.com/nasa/), namely with [Podaacpy](https://github.com/nasa/podaacpy) and [Sitepod](https://github.com/nasa/sitepod) projects. I am going to send a couple of pull requests to tidy up some of the code in pyCMR. It got me thinking that I would encourage you to take the same route and get in touch with @jasonduley such that we can begin to build more community around the pyCMR client code. 
PR's coming shortly on different tickets.
Lewis

**Comment by manilmaskey** [comment]
@lewismc: Thanks, @jasonduley is familiar with pyCMR.  We went through NASA Open Source Software release process via MSFC for pyCMR.  Having said that, always open to ways to build community around pyCMR.

**Comment by lewismc** [comment]
IMHO, I think we could build more community from other DAAC's if pyCMR were moved to the NASA Github Org. There are also some [links](https://github.com/ghrcdaac/cmr/blob/master/pyCMR/pyCMR.py#L580-L582) which are GHRC DAAC-specific... I think that is another ticket. I'll log it.

**Comment by lewismc** [comment]
@manilmaskey @amarouane any desire to transition this library to NASA Github? I've started using it over at PO.DAAC and I would like to begin building more community. I would also like to shepherd releases of the toolkit through Pypi and also condo through condo-forge.

**Comment by manilmaskey** [comment]
@lewismc go ahead.  @amarouane can provide help as needed.  Currently, it is searchable through code.nasa.gov.

**Comment by ghrcdaac** [comment]
@lewismc Yes I don't have any objections at all.

**Comment by lewismc** [comment]
OK folks, I've reached out to @jasonduley hopefully we can get the ball rolling with this one shortly.

**Comment by lewismc** [comment]
https://github.com/nasa/cmr boom
