### ISSUE TITLE
provide sample cmr.cfg

### ISSUE THREAD

**Issue by lewismc** [ghrcdaac/cmr#16]
Right now no cmr.cfg actually exists... this should be provided as it is used as the primary parameter for the CMR class.

**Comment by lewismc** [comment]
Additionally, I think the _cmr.cfg.example_ syntax should be documented on the wiki.

**Comment by manilmaskey** [comment]
@amarouane - Can you put sample cmr.cfg on wiki?

**Comment by amarouane** [comment]
I have added a sample config File

**Comment by lewismc** [comment]
Closed with commit 1aa96560e32578a2e2e9c022458d98d007e5312a
