### ISSUE TITLE
Git history vanished???

### ISSUE THREAD

**Issue by lewismc** [ghrcdaac/cmr#21]
Hi @amarouane it looks like you recently forced a overwrite and consequential deletion of the entire Git history for this project!
This seems a bit extreme for any type of software development, however please excuse me if there was/is some reasoning behind the decision.
What is the current state of the project? Is it worth me progressing with both #14 and #15?

**Comment by lewismc** [comment]
I can't even pull remote changes into my local master branch
```
lmcgibbn@LMC-056430 /usr/local/cmr(master) $ git fetch ghrcdaac
remote: Counting objects: 80, done.
remote: Total 80 (delta 26), reused 26 (delta 26), pack-reused 54
Unpacking objects: 100% (80/80), done.
From https://github.com/ghrcdaac/cmr
 * [new branch]      Development -> ghrcdaac/Development
 + 1aa9656...0bf2521 master      -> ghrcdaac/master  (forced update)
lmcgibbn@LMC-056430 /usr/local/cmr(master) $ git pull ghrcdaac master
From https://github.com/ghrcdaac/cmr
 * branch            master     -> FETCH_HEAD
fatal: refusing to merge unrelated histories
```

**Comment by lewismc** [comment]
I have just deleted my local source code and started again... this seems like a really strange and radical way of doing development @amarouane I'm a bit confused here. Please re-open if you are interested in commenting. In the meantime, I'm trying to improve and advertise uptake and usage of this library within PO.DAAC. I'll let you guys know how that goes.

**Comment by amarouane** [comment]
Hi @lewismc I am so sorry the history was deleted by mistake I accidentally pushed a password in the configfile  (the file was in gitignore) and tried to delete that particular commit but by mistake I ended up deleting the whole history. Is there and way we can recover? I will go and check if I still have history on my local branch and try to work from there. I am so sorry

**Comment by lewismc** [comment]
These things happen. Let's just move on. Please take a look at #23

**Comment by amarouane** [comment]
I want to ask you if you want to publish the Travis build results on a slack channel? or do you want to use emails?

**Comment by lewismc** [comment]
It doesn't really bother me. I am not really using slack right now to be honest but I think the notification system is useful for anyone that wishes to use it. Go ahead and do whatever you feel comfortable with.
