### ISSUE TITLE
Consider changing the project description and README to point to the actual CMR NASA Repo

### ISSUE THREAD

**Issue by steadyflux** [ghrcdaac/cmr#36]
The name of this repo is bothering me ... what most people would expect to find is actually under open source development here: https://github.com/nasa/Common-Metadata-Repository

I thought this library was called pyCMR, this repo should match that name to avoid confusion

At the very least if you can't rename the repo, please reference the actually CMR code repo in both the project description and README file.

**Comment by amarouane** [comment]
Currently on the the owner or the administrator of this repo can change it. I will try to solve this issue as soon as I have enough privilege to do it.

**Comment by vjphilli** [comment]
repo is renamed from cmr to pyCMR
